Repository UAL-RE/ReQUIAM_csv, pull requests merged in 2021-02, with the labels that each got.

#65 Type hinting throughout the code base
  README.md
  requiam_csv/__init__.py
  requiam_csv/commons.py
  requiam_csv/create_csv.py
  requiam_csv/inspect_csv.py
  requiam_csv/logger.py
  setup.py
Labels: enhancement, pep8

#67 Feature: CI Build includes Python 3.9
  .github/workflows/python-package.yml
  requirements.txt
Labels: CI/CD, enhancement

#70 hotfix/v0.11.1
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/PULL_REQUEST_TEMPLATE/bug-pull-request.md
  .github/PULL_REQUEST_TEMPLATE/feature-pull-request.md
  .github/PULL_REQUEST_TEMPLATE/release-pull-request.md
  README.md
  requiam_csv/__init__.py
  setup.py
Labels: bug
